# Last updated for SwiftLint 0.45.0

analyzer_rules:
    - unused_import

disabled_rules:
    # Would be nice to eventually have these enabled so we have more clear and performant code.
    - cyclomatic_complexity
    - function_parameter_count
    - large_tuple
    # Nesting limits will kill us in SwiftUI
    - nesting
    # This is common in SwiftUI
    - multiple_closures_with_trailing_closure

    # These conflict with SwiftFormat so they need to be disabled.
    - closure_parameter_position
    - colon
    - file_length
    - function_body_length
    - line_length
    - opening_brace
    - trailing_comma
    - type_body_length

    # Other
    - notification_center_detachment

excluded:

included:
    - ClaudeSettings
    - ClaudeSettingsPackage

opt_in_rules:
    - fatal_error_message
    - overridden_super_call
    - prohibited_super_call
    - sorted_first_last
    - quick_discouraged_focused_test
    - weak_delegate

## Rule Configuration
class_delegate_protocol: error
fatal_error_message: error # Force a message when using fatalError()
sorted_first_last: warning # max() or min() vs sort().first()
weak_delegate: error

generic_type_name:
    validates_start_with_lowercase: warning
    allowed_symbols: "_"
    min_length: 1
    max_length:
        warning: 100
        error: 120

identifier_name:
    validates_start_with_lowercase: warning # Allow _varName
    allowed_symbols: "_"
    min_length:
        warning: 0
        error: 0
    max_length:
        warning: 100
        error: 120

type_name:
    allowed_symbols: "_"
    validates_start_with_lowercase: warning
    min_length:
        warning: 1
        error: 0
    max_length:
        warning: 100
        error: 120

custom_rules:
    custom_no_number_decimals:
        name: "Remove number decimals when not needed"
        regex: '[^$".](\d+)\.0+\b(?!\d)'
        message: "Remove unnecessary decimal places from numbers"
        severity: warning
        correction:
            regex: '[^$".](\d+)\.0+\b(?!\d)'
            replacement: '$1'

    custom_sf_symbols:
        name: "Use `Symbols` enum for SFSymbols"
        regex: '(\(systemName:|systemImage:)'
        message: "When using SFSymbols, use the `Symbols` enum instead of the string value"
        severity: error
